// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.

using Content.AL.UIKit.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.AL.UIKit.Windows;

[GenerateTypedNameReferences]
public sealed partial class ALZoo : Window
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private readonly ShaderInstance? _shader;
    
    public ALZoo()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        if (_proto.TryIndex<ShaderPrototype>("ALZooDemoShader", out var s))
        {
            _shader = s.Instance();
        }
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        Backbuffer.Shader = _shader;
    }
}
